# Generated by Django 3.2.9 on 2021-11-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('n', models.CharField(max_length=100, verbose_name='Nº')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
            ],
        ),
    ]
